language: cpp
sudo: required
addons:
  apt:
    packages:
      - libgtest-dev

before_install:
 - cd /usr/src/gtest
 - sudo cmake CMakeLists.txt
 - sudo make
 - sudo cp -a libgtest_main.so libgtest.so /usr/lib/
 - cd "${TRAVIS_BUILD_DIR}"

before_script:
 - cd src

script: make
