language: cpp
sudo: required
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libgtest-dev
            - cmake
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
before_install:
 - eval "${MATRIX_EVAL}"
 - cd /usr/src/gtest
 - sudo cmake CMakeLists.txt
 - sudo make
 - sudo cp *.a /usr/lib/
 - cd "${TRAVIS_BUILD_DIR}"

before_script:
 - cd src

script: make
