language: cpp
sudo: required
addons:
  apt:
    source:
      - ubuntu-toolchain-r-test
    packages:
      - libgtest-dev
      - cmake
      - g++
env:
  - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
 - cd /usr/src/gtest
 - sudo cmake CMakeLists.txt
 - sudo make
 - sudo cp *.a /usr/lib/
 - cd "${TRAVIS_BUILD_DIR}"

before_script:
 - cd src

script: make
