language: cpp
sudo: required
addons:
  apt:
    packages:
      - libgtest-dev
      - cmake
      - g++

before_install:
 - cd /usr/src/gtest
 - sudo cmake CMakeLists.txt
 - sudo make
 - sudo cp *.a /usr/lib/
 - cd "${TRAVIS_BUILD_DIR}"

before_script:
 - cd src

script: make
