language: cpp
sudo: required
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CXX='g++-7 -Wall -std=c++11'"
before_install:
  - eval "${MATRIX_EVAL}"
script: ./gradlew check
